packages/konsistent/server/startup/loadMetaObjects.coffee, private/templates/email/resetPassword.html, server/lib/routes/app.coffee, server/methods/auth.coffee, server/startup/_loadMetaObjects.coffee
Devido aos parâmetros não estarem com valorer 'parseado' corretame foi colocado um `for in` para parsear cada valor string do objeto.
Não foi possível utilizar map, tanto ES6 quanto do Underscore devido a versão.
=> Remove Kadira, modify template e-mail and parse url params

packages/konutils/server/filterUtils.coffee
Added percentage support to Konecty's custom filters.
Issue addressed at https://gitlab.com/Konecty/www.foxterciaimobiliaria.com.br/issues/496
=> Ajustado para filtrar com percentuais

server/routes/rest/facebook/leadgen.js
Ajuste para adicionar as informações de integração do facebook para o campo de observações da oportunidade.
=> Ajuste de rest/facebook/leadgen

Dockerfile, package.json, packages/konsistent/server/lib/errors.coffee, packages/konutils/server/filterUtils.coffee, server/lib/errors.coffee
- Remove kadira
- Add more filters options for percentage field
=> Remove and add filters

packages/konsistent/lib/htmlParser.coffee, packages/konsistent/private/templates/mail/alert.html, packages/konutils/server/filterUtils.coffee
- Added an HTML parser to alert template in order to avoid HTML tags being treated as strings
- Feng shuied the hell outta **filterUtils.coffee** script
=> HTML parser adjustment

server/routes/rest/rocketchat/livechat.js
add id field on campaign to link models on procces:submit
=> add campaign id to request if there is a field identifier on campaign

packages/konutils/server/filterUtils.coffee
allow rest to filter by geolocation
=> add geolocation filter

server/routes/rest/rocketchat/livechat.js
- Remove invalid email, coming from Livechat webhook, from process payload so it doesn't break.
=> Remove invalid email from Livechat webhook

README.md, private/templates/email/resetPassword.html, server/methods/auth.js, server/routes/rest/auth/authApi.js
- Create login link for `setRandomPasswordAndSendByEmail` method
- Update _resetPassword_ template to send the login link
- Add build-essential installation step to Readme
=> Create access link when random password is generated

packages/konutils/server/filterUtils.coffee
Fix for issue https://github.com/konecty/support/issues/32
=> fix: remove empty field names from mongo projection

src/imports/data/data.js, src/imports/data/export.ts, src/imports/exports/csvExport.js, src/imports/exports/xlsExport.js, src/imports/model/User.ts, src/imports/utils/return.js, src/server/routes/rest/data/dataApi.ts
Correção da issue https://github.com/konecty/support/issues/177
=> Fix: Exports

src/imports/data/data.js, src/imports/data/dateParser/index.ts, src/imports/data/export.ts
Issue [#200](https://github.com/konecty/support/issues/200)
=> Fix: Export date formatting

src/imports/menu/legacy/index.js, src/imports/meta/applyIndexes/index.ts
Fix for issue [#122](https://github.com/konecty/support/issues/212)
=> Fix: Correct filter on date fields of list

src/imports/data/data.js, src/imports/utils/sessionUtils.ts
Fix for issue konecty/support#211
=> Fix: add contextUser to populateDetailFields

src/imports/data/data.js
Use the default query limit if the passed in limit is less or equals to 0
=> Fix: default query limit

src/imports/data/changeUser.js, src/imports/meta/getNextUserFromQueue.js
=> Fix: change user by queue

src/imports/data/export.ts, src/imports/model/Namespace.ts
Update date format for exports to match current format
=> Fix: export date format

src/imports/data/api/find.ts, src/imports/data/data.js, src/imports/data/filterUtils.js
Fix permission calculation when it references the data itself, such as in this case #142
=> Fix: Self referencing permissions

src/imports/data/filterUtils.js, src/server/routes/rest/stream/streamApi.ts
Transform phoneNumber to string on find
=> Fix: transform phoneNumber to string on find

src/imports/access/getAccessForDocument.ts, src/imports/access/updateAccess.ts, src/imports/model/MetaAccess.ts, src/imports/model/User.ts, src/imports/utils/accessUtils.ts, src/server/routes/api/access/index.ts, src/server/routes/index.ts
Api to fetch & update module access
@TODO - Create access
=> Feat / Access api

src/imports/data/changeUser.js
=> Fix: add history to change user operations

src/server/routes/rest/file/upload.ts
Use original extension for the file key
=> Fix: upload key file name

docs/en/RESOURCES_AND_EVENTS.md, src/imports/lib/EventManager.ts, src/imports/queue/QueueManager.ts, src/imports/queue/QueueResource.ts, src/imports/queue/RabbitMQResource.ts
feat: add namespace and document configuration to support delayed messages
=> Delayed Messages RabbitMQ

__test__/utils/accentToRegex.test.ts, src/imports/dne/index.js, src/imports/utils/strUtils.ts
Correção de erros de regex na busca de endereços. Aqui apago colchetes da string antes de gerar o regex, apesar de parênteses não fechados ainda darão erros (por que esses podem existir num endereço *eu acho*).
Closes #191
=> Fix: dne regex errors

src/imports/data/dateParser/index.ts, src/server/app.ts
@7sete7 essa seria uma correção para a questão das datas sumirem nos campos de data na interface antiga.
Esse problema na interface acontece apenas em campos composite, e essa mudança na API pode acarretar outros problemas que precisamos considerar. Vamos debater os impactos e possíveis outras soluções.
=> fix: format dates to UTC
